/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-01-30 06:03:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.net.*;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>boardList.jsp 게시글 리스트 </title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" 	 ");

    
    //1.드라이버연결
	Class.forName("com.mysql.jdbc.Driver");
    
  
    String url = "jdbc:mysql://localhost:3306/webmarket?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false";   
    String userId ="root";
    String userPwd="1234";
    
    //2. con 연결
    Connection con = DriverManager.getConnection(url, userId, userPwd);
    //3. sql con올리기
    String selectSql= "select * from boardtbl order by num desc";
    PreparedStatement pstmt = con.prepareStatement(selectSql);
    //4.mysql로 보내서 실행하기
    ResultSet rs = pstmt.executeQuery();
    //5.rs변수에 담겨서 select문을 jsp로 들어온다.
    
  
      out.write("\r\n");
      out.write("  \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1 class=\"display-3\"> 게시글 리스트 </h1> \r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  	    \r\n");
      out.write("    <div style=\"padding-top: 50px\">\r\n");
      out.write("	 <table class=\"table table-hover\">\r\n");
      out.write("    	<tr align=\"center\" ><th>글번호</th> <th>글제목</th> <th>작성자</th> <th>작성일</th> <th>조회수</th> <th>수정</th> <th>삭제</th></tr>\r\n");
      out.write("        ");

          while(rs.next()) { //rs.next() 꼭 써주어야 하는 명령어 포인터 위치를 가르킨다.
        	                 //한줄만 출력하더라도 반드시 rs.next() 사용해야 한다.
         
      out.write("          	                 \r\n");
      out.write("         <tr>\r\n");
      out.write("    	   <td align=\"center\" > ");
      out.print( rs.getInt("num") );
      out.write("</td>  ");
      out.write("\r\n");
      out.write("    	   <td align=\"center\" > \r\n");
      out.write("    	     <a href=\"boardDetail.jsp?num=");
      out.print(rs.getInt("num") );
      out.write("&title=");
      out.print(rs.getString("title") );
      out.write("&content=");
      out.print(rs.getString("content") );
      out.write("&writer=");
      out.print(rs.getString("writer") );
      out.write("&regdate=");
      out.print(rs.getDate("reg_date") );
      out.write("&count=");
      out.print(rs.getInt("count") );
      out.write("\" >\r\n");
      out.write("    	    \r\n");
      out.write("    	        ");
      out.print( rs.getString("title") );
      out.write(" \r\n");
      out.write("    	     </a> \r\n");
      out.write("    	   \r\n");
      out.write("    	   </td>\r\n");
      out.write("    	   <td align=\"center\" > ");
      out.print( rs.getString("writer") );
      out.write("</td>\r\n");
      out.write("    	   <td align=\"center\" > ");
      out.print( rs.getDate("reg_date") );
      out.write("</td>\r\n");
      out.write("    	   <td align=\"center\" > ");
      out.print( rs.getInt("count") );
      out.write("</td>\r\n");
      out.write("    	   <td align=\"center\" > <a href=\"boardModify.jsp?num=");
      out.print(rs.getInt("num") );
      out.write("\" class=\"btn btn-primary\"> 수정 </a> </td>\r\n");
      out.write("    	   <td align=\"center\" > <a href=\"boardDelete.jsp?num=");
      out.print(rs.getInt("num") );
      out.write("\" class=\"btn btn-danger\"> 삭제 </a> </td>\r\n");
      out.write("    	</tr>\r\n");
      out.write("         ");

          }
         
      out.write("\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("       </table>\r\n");
      out.write("       <a href=\"boardInsert.jsp\" class=\"btn btn-primary\"> 글쓰기 </a>	\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  </body>\r\n");
      out.write("  </html>\r\n");
      out.write("  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
