print("Mary\'  cosmetics")
print('신씨가 소리질렀다. "도둑이야".')
print("c:\\windows")
print("안녕하세요. \n만나서 \t\t반갑습니다")
print("오늘은", "월요일", "입니다")
print("naver", "kakao", "samsung", sep="/")
print("naver", "kakao", "samsung", sep=" - ")
print("naver", "kakao", "samsung", sep=";")
print("first", end="-->");print("second")