/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-01-29 06:23:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 String greeting = "웹 쇼핑몰에 오신 것을 환영합니다.";
      String tagline = "Welcome to Web Market!";
  
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1705464311152L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1706509399079L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>쇼핑몰</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	 <nav class=\"navbar navbar-expand navbar-dark bg-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"/WebMarket/welcome.jsp\">Home</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-header\">    \r\n");
      out.write("            <a class=\"navbar-brand\" href=\"/WebMarket/products.jsp\">전체상품</a>\r\n");
      out.write("        </div>    \r\n");
      out.write("        <div class=\"navbar-header\">    \r\n");
      out.write("            <a class=\"navbar-brand\" href=\"/WebMarket/board/boards.jsp\">게시판</a>\r\n");
      out.write("        </div>  \r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"/WebMarket/addProduct.jsp\">상품추가(판매자)</a>\r\n");
      out.write("        </div>    \r\n");
      out.write("        <div class=\"navbar-header\">    \r\n");
      out.write("             <a class=\"navbar-brand\" href=\"/WebMarket/member/memberInfo.jsp\">회원정보(관리자)</a>\r\n");
      out.write("         </div> \r\n");
      out.write("         ");

            //세션 가져오기
            String name = (String)session.getAttribute("name");
         	String id = (String )session.getAttribute("id");
         	String loginOk = "로그인";
         	if( name != null ) {
         		loginOk = name + "님 ";
         
      out.write("		\r\n");
      out.write("         <div class=\"navbar-header\">    \r\n");
      out.write("         	<div class=\"text-white\"> <h5>");
      out.print(loginOk );
      out.write(" </h5>&nbsp;&nbsp;\r\n");
      out.write("             <a class=\"navbar-brand\" href=\"/WebMarket/member/logOut.jsp\"> 로그아웃 </a>\r\n");
      out.write("         </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         ");

         		
         	}else {
         		loginOk = "로그인";
         
      out.write("	\r\n");
      out.write("         <div class=\"navbar-header\">    \r\n");
      out.write("             <a class=\"navbar-brand\" href=\"/WebMarket/member/login.jsp\">");
      out.print( loginOk );
      out.write("</a>\r\n");
      out.write("         </div>\r\n");
      out.write("         ");

         	}
         
      out.write("\r\n");
      out.write("         \r\n");
      out.write("     </div>\r\n");
      out.write("   </nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("	\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <div class=\"jumbotron\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1 class=\"display-3\"> ");
      out.print( greeting );
      out.write(" </h1> \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <main role=\"main\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"text-center\">\r\n");
      out.write("       <h3> ");
      out.print( tagline );
      out.write("</h3>\r\n");
      out.write("     \r\n");
      out.write("     ");

     Date day = new Date();
     String am_pm;
     int year = day.getYear();
     int month = day.getMonth()+1;
     int day1 = day.getDate();
     
     int hour = day.getHours();
     int minute = day.getMinutes();
     int second = day.getSeconds();
     
     if (hour / 12 == 0) am_pm = "AM";
     else { am_pm = "PM"; hour=hour-12; }
     String cd = "20" + year + "년" + month + "월" + day1 + "일";
     String ct = hour + ":" + minute + ":" + second + "" + am_pm;
     
      out.write("\r\n");
      out.write("     \r\n");
      out.write("     <h5> 방문날짜 ");
      out.print(cd );
      out.write("</h5>\r\n");
      out.write("     <h5> 방문시간 ");
      out.print(ct );
      out.write("</h5>\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  </main>   \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer class=\"container\">\r\n");
      out.write("    <p>&copy; WebMarket</p> \r\n");
      out.write("    </footer> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
